### ISSUE TITLE
子组件声明仓库后父组件更新不了

### ISSUE THREAD

**Issue by xiaohuwei** [masx200/react-simple-global-state-store-hook#1]
子组件声明状态后，父组件无法使用订阅 子组件操作仓库 父组件不更新

**Comment by masx200** [comment]
please show me your code

**Comment by masx200** [comment]
使用这个库的话,不使用 `React.createContext`,不会因为全局状态变化导致父组件刷新,只是订阅的组件更新

**Comment by masx200** [comment]
# 注意,此代码存储库已被弃用,不会再更新维护了.

# Note that this code repository has been deprecated and will not be updated and maintained.
