### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by cw19931024** [masx200/react-simple-global-state-store-hook#4]
![image](https://user-images.githubusercontent.com/15888370/79409550-d283ce80-7fd0-11ea-96ba-abe7d3166bdf.png)
![image](https://user-images.githubusercontent.com/15888370/79409583-e5969e80-7fd0-11ea-8e32-b5f2d32202df.png)
![image](https://user-images.githubusercontent.com/15888370/79409598-edeed980-7fd0-11ea-8a19-c5c4ed401e1b.png)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

看了网上的这个错误解决方案，貌似说什么版本升级到13。我从16.8升级到了13也还是不行、关键问题应该是这个useGlobalStore不支持或者是有问题。
hook我用的也不多。
求解~

**Comment by cw19931024** [comment]
看到图挂了。补个信息

全局状态文件
`import { initGlobalState } from @masx200/react-simple-global-state-store-hook;

initGlobalState({
  token: "",
  topMenuId: "",
});`

当前组件
`handleClick = (e, item, a, b) => {
    console.log(e);
    changeState("menuTop", 2222);
  }`
`const [topMenuId, setTopMenuId] = useGlobalStore("topMenuId");`

**Comment by masx200** [comment]
注意 useGlobalStore只能在函数式组件中使用,无法在类组件中使用

**Comment by masx200** [comment]
> ![image](https://user-images.githubusercontent.com/15888370/79409550-d283ce80-7fd0-11ea-96ba-abe7d3166bdf.png)
> ![image](https://user-images.githubusercontent.com/15888370/79409583-e5969e80-7fd0-11ea-8e32-b5f2d32202df.png)
> ![image](https://user-images.githubusercontent.com/15888370/79409598-edeed980-7fd0-11ea-8a19-c5c4ed401e1b.png)
> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
>    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
> 
> 看了网上的这个错误解决方案，貌似说什么版本升级到13。我从16.8升级到了13也还是不行、关键问题应该是这个useGlobalStore不支持或者是有问题。
> hook我用的也不多。
> 求解~

# 注意,此代码存储库已被弃用,不会再更新维护了.

# Note that this code repository has been deprecated and will not be updated and maintained.
